apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: blackrock30/random-mouse:1.2.2
          name: django
          ports:
            - containerPort: 8000
              name: gunicorn

---
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000